'use client';

import { ArrowDown, ArrowUpRight, Braces, Database, Mail, MapPin, PersonStanding, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';

const stages = [
  { era: '01 / Foundations', title: 'Software engineering foundations', kicker: 'SQL · APIs · problem solving', text: 'I started by learning how data moves through real applications: practical SQL, backend services, and the habits behind maintainable software.', highlights: ['Relational data modeling', 'Backend API patterns', 'Querying & troubleshooting'], tag: 'Build the reliable core' },
  { era: '02 / Systems', title: 'Backend & data systems', kicker: 'FastAPI · MongoDB · Kafka', text: 'I built service-oriented applications with APIs, authorization controls, messaging, and caching—where a clear data contract matters as much as the endpoint.', highlights: ['FastAPI / MongoDB services', 'Kafka-backed caching', 'Authorization controls'], tag: 'Connect the moving parts' },
  { era: '03 / Scale', title: 'Databricks & PySpark', kicker: 'IoT telemetry · distributed processing', text: 'I worked on telemetry-style pipelines that turn high-volume events into usable data sets, applying PySpark patterns for transformation and operational clarity.', highlights: ['Databricks notebooks', 'PySpark transformations', 'IoT telemetry pipelines'], tag: 'Make streams useful' },
  { era: '04 / Analytics', title: 'Snowflake & dbt', kicker: 'Staging → marts · incremental models', text: 'I built analytics-ready transformations from staged source data through curated marts, using incremental processing and SQL tuned for dependable reporting.', highlights: ['dbt model layering', 'Incremental processing', 'SQL performance work'], tag: 'Turn raw data into answers' },
  { era: '05 / Now', title: 'Azure IaC & current work', kicker: 'Cloud foundations · reproducible delivery', text: 'I bring software discipline to modern cloud data work: infrastructure as code, clear environments, and systems designed to be understood after they ship.', highlights: ['Azure infrastructure as code', 'Cloud data platforms', 'Operational documentation'], tag: 'Make delivery repeatable' },
];

const projects = [
  { type: 'Analytics engineering', title: 'From staged data to trusted marts', body: 'A layered Snowflake + dbt approach for moving source data through explicit staging, transformations, and analytical models with incremental patterns where they fit.', tools: ['Snowflake', 'dbt', 'SQL'] },
  { type: 'Data pipelines', title: 'Telemetry in motion', body: 'Databricks and PySpark pipelines shaped around IoT-style telemetry: parse events, transform at scale, and make the resulting data useful downstream.', tools: ['Databricks', 'PySpark', 'Azure'] },
  { type: 'Software systems', title: 'Services that know their boundaries', body: 'Backend applications using FastAPI, MongoDB, Kafka, PostgreSQL, GraphQL, and RabbitMQ—with attention to authorization, messaging, and cache-aware behavior.', tools: ['FastAPI', 'Kafka', 'PostgreSQL'] },
];

function DataMap() { return <div className="data-map" aria-label="An abstract map of Abhinandan's data engineering toolkit"><svg className="map-lines" viewBox="0 0 920 550" role="img" aria-hidden="true"><defs><linearGradient id="flow" x1="0" x2="1"><stop stopColor="#3b82f6" stopOpacity=".12" /><stop offset=".5" stopColor="#62c6ff" /><stop offset="1" stopColor="#f3a64f" stopOpacity=".48" /></linearGradient></defs><path d="M98 118 C212 95 253 206 360 190 S497 67 572 131 S691 217 814 150" /><path d="M70 384 C189 323 245 410 352 367 S475 285 579 349 S707 469 841 393" /><path d="M189 93 C157 204 273 244 351 368 S515 468 612 359 S739 253 816 151" /><path d="M98 118 C175 245 213 311 70 384" className="subtle" /><path d="M360 190 C421 250 468 282 579 349" className="subtle" /></svg><div className="map-orbit orbit-one" /><div className="map-orbit orbit-two" /><div className="map-node node-snowflake"><span className="node-mark">✳</span><b>Snowflake</b><small>analytics cloud</small></div><div className="map-node node-dbt"><span className="node-mark">↗</span><b>dbt</b><small>data models</small></div><div className="map-node node-databricks"><span className="node-mark">≋</span><b>Databricks</b><small>PySpark jobs</small></div><div className="map-node node-azure"><span className="node-mark">⌘</span><b>Azure IaC</b><small>cloud foundations</small></div><div className="map-node node-sql"><span className="node-mark">⌁</span><b>SQL</b><small>query craft</small></div><div className="map-node node-api"><span className="node-mark">⌘</span><b>APIs / Kafka</b><small>systems in motion</small></div><span className="signal signal-one" /><span className="signal signal-two" /><span className="signal signal-three" /></div>; }

export default function Home() {
  const [progress, setProgress] = useState(0); const [activeStage, setActiveStage] = useState(0);
  useEffect(() => { const onScroll = () => { const max = Math.max(1, document.documentElement.scrollHeight - window.innerHeight); const next = Math.min(1, window.scrollY / max); setProgress(next); setActiveStage(Math.min(stages.length - 1, Math.floor(next * stages.length))); }; onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll); }, []);
  return <main>
    <section className="hero" id="top"><nav className="nav-shell" aria-label="Main navigation"><a href="#top" className="monogram" aria-label="Back to the top">AK</a><div className="nav-links"><a href="#journey">Journey</a><a href="#work">Work</a><a href="#about">About</a></div><a href="#contact" className="nav-contact">Let&apos;s connect <ArrowUpRight size={15} /></a></nav><div className="hero-copy"><p className="eyebrow"><span /> Data Engineer &amp; Software Builder</p><h1>Designing the paths<br />that make data <em>useful.</em></h1><p className="hero-intro">I build the infrastructure, models, and services behind clear decisions—drawing on nearly 3 years across software engineering and modern cloud data platforms.</p><div className="hero-actions"><a href="#journey" className="button-primary">Follow the journey <ArrowDown size={16} /></a><a href="#work" className="quiet-link">Selected work <span>↗</span></a></div></div><DataMap /><div className="hero-footer"><span>Scroll to travel the map</span><span className="hero-status"><i /> Available for thoughtful work</span></div></section>
    <section className="journey" id="journey"><div className="section-top"><p className="eyebrow"><span /> The journey</p><p>A practical progression from code to cloud data.</p></div><div className="journey-grid"><aside className="road-panel" aria-label={`Journey progress: stage ${activeStage + 1} of ${stages.length}`}><div className="road-label"><span>START</span><span>NOW</span></div><div className="road-track"><div className="road-fill" style={{ height: `${Math.max(4, progress * 100)}%` }} />{stages.map((stage, index) => <a key={stage.title} className={`road-stop ${index === activeStage ? 'is-active' : ''}`} style={{ top: `${7 + index * 21.5}%` }} href={`#stage-${index}`} aria-label={`Jump to ${stage.title}`}><span>{String(index + 1).padStart(2, '0')}</span></a>)}<div className="traveler" style={{ top: `${Math.min(90, 4 + progress * 88)}%` }}><PersonStanding size={23} strokeWidth={1.75} /><i /></div></div></aside><div className="stage-list">{stages.map((stage, index) => <article className={`stage-card stage-${index}`} id={`stage-${index}`} key={stage.title}><div className="stage-number">{stage.era}</div><div><p className="stage-kicker">{stage.kicker}</p><h2>{stage.title}</h2><p className="stage-text">{stage.text}</p></div><div className="stage-meta"><span>{stage.tag}</span><ul>{stage.highlights.map((item) => <li key={item}>{item}</li>)}</ul></div></article>)}</div></div></section>
    <section className="work-section" id="work"><div className="section-top"><p className="eyebrow"><span /> Selected work</p><p>Systems thinking, from the event to the answer.</p></div><div className="project-grid">{projects.map((project, index) => <article className="project-card" key={project.title}><div className="project-top"><span>0{index + 1}</span><span className="project-type">{project.type}</span><ArrowUpRight size={18} /></div><div className="project-mark">{index === 0 ? <Database size={34} /> : index === 1 ? <Sparkles size={34} /> : <Braces size={34} />}</div><h3>{project.title}</h3><p>{project.body}</p><div className="tool-row">{project.tools.map((tool) => <span key={tool}>{tool}</span>)}</div></article>)}</div></section>
    <section className="about-section" id="about"><div className="about-stamp">AK <span>•</span> 03 YEARS <span>•</span> INDIA</div><div><p className="eyebrow"><span /> About Abhinandan</p><h2>Curious about the space between a dataset and a decision.</h2><p>I&apos;m a data engineer and software builder who enjoys making complex systems legible. My path began with backend services and SQL, and grew into cloud data work across Snowflake, dbt, Databricks, PySpark, and Azure.</p><p>The common thread: reliable foundations, intentional interfaces, and data that earns its place in the conversation.</p></div><div className="stack-panel"><p>Core stack</p><div>{['Snowflake','dbt','SQL','Databricks','PySpark','Azure','FastAPI','Kafka','PostgreSQL','GraphQL','RabbitMQ','MongoDB'].map((item) => <span key={item}>{item}</span>)}</div></div></section>
    <section className="contact-section" id="contact"><div><p className="eyebrow"><span /> The next stop</p><h2>Have a hard data problem?<br /><em>Let&apos;s make it clearer.</em></h2></div><div className="contact-button" aria-label="Contact invitation">Start a conversation <Mail size={18} /></div><p className="contact-note"><MapPin size={14} /> Open to data engineering &amp; software opportunities</p></section><footer><span>© {new Date().getFullYear()} Abhinandan Kumar</span><a href="#top">Back to top ↑</a></footer>
  </main>;
}
